### ISSUE TITLE
Lesson will not open with learn app

### ISSUE THREAD

**Issue by MrSnickers** [learn-co-curriculum/pry-readme#25]
The companion Learn app is unable to open this lesson.  It did open the previous ones.  The error message is:
Hmm...Cannot find lesson with repo: debugging-with-pry-000. Please check your input and try again.

**Comment by AnnJohn** [comment]
hi @MrSnickers sorry for the issue that you're having. Since this is a technical issue, can you file a bug report (if you hover over your profile pic in Learn, you'll see a menu with the option to file a bug report) and use the Ask a Question tool? Using 'Ask a Question' is the fastest way to get a response. Thanks!
